[project]
name = "python_library_example"
version = "v0.5"
authors = [
  { name="joanplaja", email="joanplaja10@gmail.com" },
]
readme = "README.md"
description = ""
requires-python = ">=3.6"

[tool.pytest.ini_options]
pythonpath = [
  "src"
]